baseURL = 'https://realcolordream.github.io/Portfolio/'
languageCode = 'fr'                                     # Default language
title = 'Portfolio'
theme = "terminal"
# paginate = 5 deprecated
pagination.pagerSize = 5

[params]
contentTypeName = "posts"
showMenuItems = 3
showLanguageSelector = true
fullWidthTheme = false
centerTheme = true
autoCover = true
# showLastUpdated = true
readingTime = true
# Toc = true
# TocTitle = "Table of Contents"


[languages]
[languages.en]
weight = 1
languageName = "English"
title = "My Portfolio"

[languages.en.params]
subtitle = "A simple, retro theme for Hugo"
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"

[languages.en.params.logo]
logoText = "RealColorDream - en"
logoHomeLink = "/Portfolio/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "School projects"
name = "School projects"
url = "/school"

[[languages.en.menu.main]]
identifier = "personal-projects"
name = "Personal Projects"
url = "/works"

[[languages.en.menu.main]]
identifier = "skills"
name = "Skills"
url = "/skills"

[languages.fr]
weight = 2
languageName = "French"
title = "Mon Portfolio"

[languages.fr.params]
subtitle = "A simple, retro theme for Hugo"
menuMore = "Afficher plus"
readMore = "Voir plus"
readOtherPosts = "Lire un autre post"
newerPosts = "Nouveaux posts"
olderPosts = "Ancien posts"
missingContentMessage = "Page non trouver ..."
missingBackButtonLabel = "Page principale"
minuteReadingTime = "min de lecture"
words = "mots"

[languages.fr.params.logo]
logoText = "RealColorDream - fr"
logoHomeLink = "/Portfolio/fr/"

[languages.fr.menu]
[[languages.fr.menu.main]]
identifier = "1"
name = "Projets scolaires"
url = "/fr/school/"
weight = 2

[[languages.fr.menu.main]]
identifier = "2"
name = "Projets personnels"
url = "/fr/works/"
weight = 1

[[languages.fr.menu.main]]
identifier = "3"
name = "Compétences"
url = "/fr/skills/"
weight = 3

#[[languages.fr.menu.main]]
#identifier = "posts"
#name = "Posts"
#url = "/fr/posts/"


[languages.ru]
weight = 3
languageName = "Russian"
title = "Мое Портфолио"

[languages.ru.params]
subtitle = "Простая, ретро тема для Hugo"
menuMore = "Показать больше"
readMore = "Читать далее"
readOtherPosts = "Читать другие посты"
newerPosts = "Новые посты"
olderPosts = "Старые посты"
missingContentMessage = "Страница не найдена..."
missingBackButtonLabel = "Вернуться на главную страницу"
minuteReadingTime = "мин чтения"
words = "слова"

[languages.ru.params.logo]
logoText = "RealColorDream - ru"
logoHomeLink = "/Portfolio/ru/"

[languages.ru.menu]
[[languages.ru.menu.main]]
identifier = "school-projects"
name = "Школьные проекты"
url = "/ru/school"
weight = 2

[[languages.ru.menu.main]]
identifier = "personal-projects"
name = "Личные проекты"
url = "/ru/works"
weight = 1

[[languages.ru.menu.main]]
identifier = "skills"
name = "Навыки"
url = "/ru/skills"
weight = 3